spring.application.name=Terceros
server.port=${PORT:8080}
logging.level.org.atmosphere=warn

vaadin.launch-browser=true

vaadin.allowed-packages=com.vaadin,org.vaadin,com.flowingcode,com.example

spring.datasource.url=jdbc:postgresql://localhost:5432/terceros_BD
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
